import type { Locale } from "@/lib/balatroLocale"

/**
 * Official challenge display names per locale, lifted from the game's
 * `challenge_names` localization tables (en-us / zh_CN / zh_TW / ja / ko).
 */
export const challengeNamesByLocale: Record<Locale, Record<string, string>> = {
  en: {
    c_blast_off_1: "Blast Off",
    c_bram_poker_1: "Bram Poker",
    c_city_1: "15 Minute City",
    c_cruelty_1: "Cruelty",
    c_double_nothing_1: "Double or Nothing",
    c_five_card_1: "Five-Card Draw",
    c_fragile_1: "Fragile",
    c_golden_needle_1: "Golden Needle",
    c_inflation_1: "Inflation",
    c_jokerless_1: "Jokerless",
    c_knife_1: "On a Knife's Edge",
    c_luxury_1: "Luxury Tax",
    c_mad_world_1: "Mad World",
    c_medusa_1: "Medusa",
    c_monolith_1: "Monolith",
    c_non_perishable_1: "Non-Perishable",
    c_omelette_1: "The Omelette",
    c_rich_1: "Rich get Richer",
    c_typecast_1: "Typecast",
    c_xray_1: "X-ray Vision",
  },
  "zh-CN": {
    c_blast_off_1: "点火升空",
    c_bram_poker_1: "布莱姆·扑克",
    c_city_1: "15分钟都市",
    c_cruelty_1: "残酷",
    c_double_nothing_1: "孤注一掷",
    c_five_card_1: "五连抽",
    c_fragile_1: "易碎品",
    c_golden_needle_1: "金针",
    c_inflation_1: "通货膨胀",
    c_jokerless_1: "无小丑",
    c_knife_1: "刀锋之上",
    c_luxury_1: "奢侈税",
    c_mad_world_1: "疯狂世界",
    c_medusa_1: "美杜莎",
    c_monolith_1: "巨石",
    c_non_perishable_1: "不腐之物",
    c_omelette_1: "煎蛋卷",
    c_rich_1: "富者愈富",
    c_typecast_1: "角色固化",
    c_xray_1: "X光视界",
  },
  "zh-TW": {
    c_blast_off_1: "一飛沖天",
    c_bram_poker_1: "布蘭撲克",
    c_city_1: "一刻鐘城市",
    c_cruelty_1: "殘忍無情",
    c_double_nothing_1: "孤注一擲",
    c_five_card_1: "五張換牌",
    c_fragile_1: "脆弱不堪",
    c_golden_needle_1: "黃金針",
    c_inflation_1: "通貨膨脹",
    c_jokerless_1: "小丑不再",
    c_knife_1: "刀鋒之上",
    c_luxury_1: "奢侈稅",
    c_mad_world_1: "瘋狂世界",
    c_medusa_1: "梅杜莎",
    c_monolith_1: "巨石柱",
    c_non_perishable_1: "保久物資",
    c_omelette_1: "煎蛋捲",
    c_rich_1: "富者愈富",
    c_typecast_1: "定型角色",
    c_xray_1: "透視眼",
  },
  ja: {
    c_blast_off_1: "吹き飛ばし",
    c_bram_poker_1: "ブラムポーカー",
    c_city_1: "15分都市",
    c_cruelty_1: "残虐",
    c_double_nothing_1: "一か八か",
    c_five_card_1: "ファイブカードドロー",
    c_fragile_1: "フラジャイル",
    c_golden_needle_1: "ゴールデンニードル",
    c_inflation_1: "インフレ",
    c_jokerless_1: "ジョーカーなし",
    c_knife_1: "紙一重",
    c_luxury_1: "ぜいたく税",
    c_mad_world_1: "狂気の世界",
    c_medusa_1: "メデューサ",
    c_monolith_1: "一枚岩",
    c_non_perishable_1: "保存食",
    c_omelette_1: "オムレツ",
    c_rich_1: "大富豪",
    c_typecast_1: "はまり役",
    c_xray_1: "透視能力",
  },
  ko: {
    c_blast_off_1: "발사",
    c_bram_poker_1: "브램 포커",
    c_city_1: "15분 도시",
    c_cruelty_1: "잔인함",
    c_double_nothing_1: "두 배 또는 꽝",
    c_five_card_1: "카드 5장 뽑기",
    c_fragile_1: "연약함",
    c_golden_needle_1: "골든 바늘",
    c_inflation_1: "인플레이션",
    c_jokerless_1: "조커 없음",
    c_knife_1: "칼끝에서",
    c_luxury_1: "특별 소비세",
    c_mad_world_1: "미친 세계",
    c_medusa_1: "메두사",
    c_monolith_1: "모노리스",
    c_non_perishable_1: "비부패",
    c_omelette_1: "오믈렛",
    c_rich_1: "부자가 더 부자로",
    c_typecast_1: "정형화",
    c_xray_1: "엑스레이 시야",
  },
}
